### ISSUE TITLE
[MJAVADOC-279] Javadoc plugin doesn't set dependencies correctly when pom uses classifiers

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#577]
**[James Nichols](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zak_spede)** opened **[MJAVADOC-279](https://issues.apache.org/jira/browse/MJAVADOC-279?redirect=false)** and commented

Create a project which has dependencies like:

```xml
<dependencies>
    <dependency>  
        <groupId>com.xxx</groupId>  
        <artifactId>mydep</artifactId>  
        <version>1.3.1</version>            
        <classifier>core</classifier>  
    </dependency>
    <dependency>  
        <groupId>com.xxx</groupId>  
        <artifactId>mydep</artifactId>  
        <version>1.3.1</version>            
        <classifier>util</classifier> 
    </dependency>
</dependencies>
```

This will add dependencies to the javadoc options file something like this:

classpath
'C:/dev/target/classes;c:/repository/com/xxx/mydep/1.3.1/mydep-1.3.1-core.jar;c:/repository/com/xxx/mydep/1.3.1/mydep-1.3.1-core.jar'

where it should yield:

classpath
'C:/dev/target/classes;c:/repository/com/xxx/mydep/1.3.1/mydep-1.3.1-core.jar;c:/repository/com/xxx/mydep/1.3.1/mydep-1.3.1-util.jar'

i.e. the classifier for the artifacts is being ignored. This causes various dependencies to be missing from the javadoc task which will eventually fail with:

```
java.lang.NullPointerException
        at com.sun.tools.javadoc.TypeMaker.getType(TypeMaker.java:67)
        at com.sun.tools.javadoc.TypeMaker.getType(TypeMaker.java:29)
        at com.sun.tools.javadoc.ClassDocImpl.superclassType(ClassDocImpl.java:441)
        at com.sun.tools.doclets.internal.toolkit.util.Util.getAllInterfaces(Util.java:386)
        at com.sun.tools.doclets.internal.toolkit.util.Util.getAllInterfaces(Util.java:424)
        at com.sun.tools.doclets.internal.toolkit.util.ClassTree.processType(ClassTree.java:162)
        at com.sun.tools.doclets.internal.toolkit.util.ClassTree.buildTree(ClassTree.java:114)
        at com.sun.tools.doclets.internal.toolkit.util.ClassTree.<init>(ClassTree.java:73)
        at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:104)
        at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.start(AbstractDoclet.java:64)
        at com.sun.tools.doclets.formats.html.HtmlDoclet.start(HtmlDoclet.java:42)
        at com.sun.tools.doclets.standard.Standard.start(Standard.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:215)
        at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:91)
        at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:340)
        at com.sun.tools.javadoc.Start.begin(Start.java:128)
        at com.sun.tools.javadoc.Main.execute(Main.java:41)
        at com.sun.tools.javadoc.Main.main(Main.java:31)
```

---

**Affects:** 2.6.1

**Attachments:**
- [mazix.zip](https://issues.apache.org/jira/secure/attachment/12717040/mazix.zip) (_7.99 kB_)
- [mazix-mvn-logs.zip](https://issues.apache.org/jira/secure/attachment/12717063/mazix-mvn-logs.zip) (_4.42 kB_)

**Issue Links:**
- [MJAVADOC-302](https://issues.apache.org/jira/browse/MJAVADOC-302) Classpath cleared after maven-javadoc-plugin:javadoc
 (_**"is duplicated by"**_)
- [MPIR-223](https://issues.apache.org/jira/browse/MPIR-223) Dependency report introduces corruption in classpaths for other plugins
 (_**"depends upon"**_)

2 votes, 2 watchers

**Comment by jira-importer** [comment]
**[James Nichols](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zak_spede)** commented

this occurs when running site goal; works fine for javadoc:javadoc

**Comment by jira-importer** [comment]
**[Leonardo Uribe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lu4242)** commented

I have a similar problem in myfaces core project. I'm using maven 2.0.10 but this one can also be reproduced with maven 2.2.1:

http://svn.apache.org/repos/asf/myfaces/core/trunk/

we have two modules: api and impl. With maven site plugin 2.0-beta-6 everything works fine, but when I try to change it to 2.0-beta-7 (on trunk/pom.xml)  or upper, the javadoc plugin report on impl cannot find myfaces api on the classpath. I tried every maven javadoc plugin version from 2.3 without success.

It only can be reproduced when site is deployed. The command there is:

mvn clean install site -Pgenerate-site -Pgenerate-tlddoc

I think the reason behind that behavior is the classpath for maven javadoc report plugin is not correctly set. Note when site goal runs, in theory the classloader should not contains all compile or provided dependencies of the module pom, but on 2.0-beta-6 this is not true. I think that all versions of maven javadoc plugin assume the oposite, and that's the reason why it works well on 2.0-beta-6 and not later.

One solution for use an upper site plugin version is do not generate the javadoc as a report and do it directly. The javadoc report will not appear on the project reports page but it is best than nothing.

**Comment by jira-importer** [comment]
**[Benjamin Croizet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bct)** commented

Hello all,

I have also this kind of problem with a multi modules project using classifier dependencies but it is not a NullPointerException, just a build error when trying to generate the javadoc through the _*mvn site*_ command.

Here is an extract of the error :

```
1 error
1 warning
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error during page generation

Embedded error: Error rendering Maven report: 
Exit code: 1 - /home/bcroizet/mazix/mazix-persistence/src/main/java/net/sourceforge/mazix/persistence/FileConstants.java:3: cannot find symbol
symbol  : class CommonFileConstants
location: package net.sourceforge.mazix.components
import net.sourceforge.mazix.components.CommonFileConstants;
```

To help you, I have attached all files needed to reproduce the problem :
1. [^mazix.zip] which contains the simplest project to reproduce the bug, containing a parent project and its two modules with **pom.xml** files
2. [^mazix-mvn-logs.zip] which contains all output logs file of **mvn** commands, and also my _*mvn -version*_ output log.

It is really strange because it works well with _*mvn javadoc:javadoc*_ command.
I'm using the latest versions of maven (2.2.1) and maven-javadoc plugin (2.6.1)

Do you have any idea about this issue ?
Thanks a lot for your help

**Comment by jira-importer** [comment]
**[Josh Spiewak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jss)** commented

I was seeing the symptoms of MJAVADOC-298 (javadoc failure due to annotations not being found on the classpath), and seem to have tracked the cause of that down to this issue.

When my module's dependencies are in this order:

```
<dependency>
    <groupId>com.brightcove.bumblebee</groupId>
    <artifactId>bumblebee-domain</artifactId>
    <version>1.24-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>com.brightcove.bumblebee</groupId>
    <artifactId>bumblebee-domain</artifactId>
    <version>1.24-SNAPSHOT</version>
    <classifier>tests</classifier>
    <scope>test</scope>
</dependency>
```

I end up with bumblebee-domain-1.24-SNAPSHOT-tests.jar in the javadoc classpath (when running site, not javadoc:javadoc), but not the regular jar (I ran the plugin with debug true to preserve the options file which is where you can see the classpath).  If I swap the order, I end up, correctly, with bumblebee-domain-1.24-SNAPSHOT.jar.

This happens for both maven-javadoc-plugin 2.6.1 and 2.7

**Comment by jira-importer** [comment]
**[Joerg Schaible](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joehni)** commented

And it happens for M2 only (at least using site plugin 2.1.1), but not for M3 with site-plugin 3.0-beta-2.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

after searching, I found that the problem is caused by maven-project-info-report-plugin 2.1, 2.3 or 2.3.1
2.1.1 and 2.2 don't cause this failure
the issue is tracked as MPIR-223
