### ISSUE TITLE
[MJAVADOC-737]  error: cannot find symbol  @Test since plugin version 3.3.0

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#1109]
**[Kai Hofmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=powerstat)** opened **[MJAVADOC-737](https://issues.apache.org/jira/browse/MJAVADOC-737?redirect=false)** and commented

After updating maven-javadoc-plugin from 3.2.0 to 3.4.1 I got the following error messages for my test code only, when executing 

```java
mvn site
```

Constructing Javadoc information...
100 errors
[ERROR] Error while creating javadoc report:
Exit code: 1 - C:\Users\PowerStat\Documents\TemplateEngine\src\test\java\de\powerstat\phplib\templateengine\test\TemplateEngineTests.java:7: error: package org.junit.jupiter.api does not exist
import static org.junit.jupiter.api.Assertions.assertAll;

[...]

C:\Users\PowerStat\Documents\TemplateEngine\src\test\java\de\powerstat\phplib\templateengine\test\TemplateEngineTests.java:27: error: package org.junit.jupiter.api does not exist
import org.junit.jupiter.api.Test;
                            ^
C:\Users\PowerStat\Documents\TemplateEngine\src\test\java\de\powerstat\phplib\templateengine\test\TemplateEngineTests.java:31: error: package edu.umd.cs.findbugs.annotations does not exist
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
                                      ^
C:\Users\PowerStat\Documents\TemplateEngine\src\test\java\de\powerstat\phplib\templateengine\test\TemplateEngineTests.java:37: error: cannot find symbol
`@SuppressFBWarnings`({"CE_CLASS_ENVY", "EC_NULL_ARG"})
 ^
  symbol: class SuppressFBWarnings
C:\Users\PowerStat\Documents\TemplateEngine\src\test\java\de\powerstat\phplib\templateengine\test\TemplateEngineTests.java:342: error: cannot find symbol
  `@Test`
   ^

[...]

Command line was: cmd.exe /X /C ""C:\Program Files\Java\jdk-11.0.10\bin\javadoc.exe" `@options` `@packages` `@argfile`"

Refer to the generated Javadoc files in 'C:\Users\PowerStat\Documents\TemplateEngine\target\site\testapidocs' dir.

org.apache.maven.reporting.MavenReportException:
Exit code: 1 - C:\Users\PowerStat\Documents\TemplateEngine\src\test\java\de\powerstat\phplib\templateengine\test\TemplateEngineTests.java:7: error: package org.junit.jupiter.api does not exist
import static org.junit.jupiter.api.Assertions.assertAll;

[...]

C:\Users\PowerStat\Documents\TemplateEngine\src\test\java\de\powerstat\phplib\templateengine\test\TemplateEngineTests.java:37: error: cannot find symbol
`@SuppressFBWarnings`({"CE_CLASS_ENVY", "EC_NULL_ARG"})
 ^
  symbol: class SuppressFBWarnings
C:\Users\PowerStat\Documents\TemplateEngine\src\test\java\de\powerstat\phplib\templateengine\test\TemplateEngineTests.java:342: error: cannot find symbol
  `@Test`
   ^
  symbol:   class Test
  location: class TemplateEngineTests

[...]

Command line was: cmd.exe /X /C ""C:\Program Files\Java\jdk-11.0.10\bin\javadoc.exe" `@options` `@packages` `@argfile`"

Refer to the generated Javadoc files in 'C:\Users\PowerStat\Documents\TemplateEngine\target\site\testapidocs' dir.

    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.doExecuteJavadocCommandLine (AbstractJavadocMojo.java:6092)
    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeJavadocCommandLine (AbstractJavadocMojo.java:5968)
    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeReport (AbstractJavadocMojo.java:2277)
    at org.apache.maven.plugins.javadoc.TestJavadocReport.executeReport (TestJavadocReport.java:162)
    at org.apache.maven.plugins.javadoc.JavadocReport.generate (JavadocReport.java:150)
    at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument (ReportDocumentRenderer.java:226)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render (DefaultSiteRenderer.java:349)
    at org.apache.maven.plugins.site.render.SiteMojo.renderLocale (SiteMojo.java:194)
    at org.apache.maven.plugins.site.render.SiteMojo.execute (SiteMojo.java:143)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)

 

With Version 3.2.0 I don't have these.

 

---

**Affects:** 3.3.0, 3.3.1, 3.3.2, 3.4.0, 3.4.1

**Comment by jira-importer** [comment]
**[Kai Hofmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=powerstat)** commented

I have already tested all versions between - thats why I all marked them as affected.

**Comment by jira-importer** [comment]
**[Elliotte Rusty Harold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elharo)** commented

Do you have a repro? At first glance, I'm guessing that the pom.xml does not properly declare its test dependencies and that in earlier versions of the plugin, we were improperly adding something to your project's classpath. Just a guess, but it's hard to be sure without seeing your code.

**Comment by jira-importer** [comment]
**[Kai Hofmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=powerstat)** commented

See **External issue URL**

**Comment by jira-importer** [comment]
**[Elliotte Rusty Harold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elharo)** commented

Just a guess but try changing

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.9.1</version>
    </dependency>

to

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.9.1</version>
    </dependency>

or at least add a dependency on org.junit.jupiter:junit-jupiter

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fix your project please:

```
D:\Entwicklung\Projekte\TemplateEngine [master ≡ +0 ~1 -0 !]> git --no-pager diff
diff --git a/pom.xml b/pom.xml
index 5161ae6..6d1151d 100644
--- a/pom.xml
+++ b/pom.xml
@@ -147,7 +147,7 @@
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-javadoc-plugin</artifactId>
-        <version>3.4.1</version>
+        <version>3.5.0</version>
         <configuration>
           <show>protected</show>
           <failOnError>false</failOnError>
@@ -162,33 +162,17 @@
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-surefire-plugin</artifactId>
-        <version>2.22.2</version>
+        <version>3.0.0-M8</version>
         <configuration>
           <forkCount>1</forkCount> <!-- 0 -->
           <trimStackTrace>false</trimStackTrace>
         </configuration>
-        <dependencies>
-          <dependency>
-            <groupId>org.junit.jupiter</groupId>
-            <artifactId>junit-jupiter-engine</artifactId>
-            <version>5.9.1</version>
-          </dependency>
-
-        </dependencies>
       </plugin>

       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-failsafe-plugin</artifactId>
-        <version>2.22.2</version>
-        <dependencies>
-          <dependency>
-            <groupId>org.junit.jupiter</groupId>
-            <artifactId>junit-jupiter-engine</artifactId>
-            <version>5.9.1</version>
-          </dependency>
-
-        </dependencies>
+        <version>3.0.0-M8</version>
         <configuration>
           <trimStackTrace>false</trimStackTrace>
         </configuration>
@@ -414,7 +398,7 @@
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-site-plugin</artifactId>
-        <version>3.9.1</version>
+        <version>3.12.1</version>
         <dependencies>
           <dependency>
             <groupId>org.apache.maven.wagon</groupId>
@@ -678,7 +662,7 @@
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-surefire-report-plugin</artifactId>
-        <version>2.22.2</version>
+        <version>3.0.0-M8</version>
         <configuration>
         </configuration>
       </plugin>
@@ -762,7 +746,7 @@
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-javadoc-plugin</artifactId>
-        <version>3.4.1</version>
+        <version>3.5.0</version>
         <configuration>
           <show>private</show>
           <failOnError>false</failOnError>
@@ -807,9 +791,15 @@
   </reporting>

   <dependencies>
+    <dependency>
+      <groupId>org.junit.platform</groupId>
+      <artifactId>junit-platform-suite-api</artifactId>
+      <version>1.9.1</version>
+      <scope>test</scope>
+    </dependency>
     <dependency>
       <groupId>org.junit.jupiter</groupId>
-      <artifactId>junit-jupiter-engine</artifactId>
+      <artifactId>junit-jupiter-api</artifactId>
       <version>5.9.1</version>
       <scope>test</scope>
     </dependency>
@@ -854,13 +844,6 @@
       <scope>test</scope>
     </dependency>

-    <dependency>
-      <groupId>org.junit.platform</groupId>
-      <artifactId>junit-platform-suite</artifactId>
-      <version>1.9.1</version>
-      <scope>test</scope>
-    </dependency>
-
    </dependencies>

 </project>
```

now

```
D:\Entwicklung\Projekte\TemplateEngine [master ≡ +0 ~1 -0 !]> mvn clean site -V
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: D:\Entwicklung\Programme\apache-maven-3.8.7
Java version: 11.0.14, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-11.0.14.9-hotspot
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] -----------------< de.powerstat.phplib:templateengine >-----------------
[INFO] Building PowerStatsTemplateEngine 1.7-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.2.0:clean (default-clean) @ templateengine ---
...
[INFO] Generating "Javadoc" report       --- maven-javadoc-plugin:3.5.0:aggregate-no-fork
[INFO] No previous run data found, generating javadoc.
[INFO]
Loading source file D:\Entwicklung\Projekte\TemplateEngine\src\main\java\module-info.java...
Loading source files for package de.powerstat.phplib.templateengine...
Constructing Javadoc information...
Standard Doclet version 11.0.14
Building tree for all the packages and classes...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\de.powerstat.phplib.templateengine\de\powerstat\phplib\templateengine\TemplateEngine.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\de.powerstat.phplib.templateengine\de\powerstat\phplib\templateengine\TemplateEngine.HandleUndefined.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\de.powerstat.phplib.templateengine\de\powerstat\phplib\templateengine\package-summary.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\de.powerstat.phplib.templateengine\de\powerstat\phplib\templateengine\package-tree.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\de.powerstat.phplib.templateengine\module-summary.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\constant-values.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\de.powerstat.phplib.templateengine\de\powerstat\phplib\templateengine\class-use\TemplateEngine.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\de.powerstat.phplib.templateengine\de\powerstat\phplib\templateengine\class-use\TemplateEngine.HandleUndefined.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\de.powerstat.phplib.templateengine\de\powerstat\phplib\templateengine\package-use.html...
Building index for all the packages and classes...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\overview-tree.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\index-all.html...
Building index for all classes...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\allclasses-index.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\allpackages-index.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\deprecated-list.html...
Building index for all classes...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\allclasses.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\allclasses.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\index.html...
Generating D:\Entwicklung\Projekte\TemplateEngine\target\site\apidocs\help-doc.html...
[INFO] Generating "Test Javadoc" report  --- maven-javadoc-plugin:3.5.0:test-aggregate-no-fork
[INFO] Configuration changed, re-generating javadoc.
[INFO]
Loading source files for package de.powerstat.phplib.templateengine...
1 error
[ERROR] Error while creating javadoc report:
Exit code: 2
javadoc: error - No source files for package de.powerstat.phplib.templateengine
Command line was: cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-11.0.14.9-hotspot\bin\javadoc.exe" @options @packages"

Refer to the generated Javadoc files in 'D:\Entwicklung\Projekte\TemplateEngine\target\site\testapidocs' dir.

org.apache.maven.reporting.MavenReportException:
Exit code: 2
javadoc: error - No source files for package de.powerstat.phplib.templateengine
Command line was: cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-11.0.14.9-hotspot\bin\javadoc.exe" @options @packages"

Refer to the generated Javadoc files in 'D:\Entwicklung\Projekte\TemplateEngine\target\site\testapidocs' dir.

    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.doExecuteJavadocCommandLine (AbstractJavadocMojo.java:5166)
    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeJavadocCommandLine (AbstractJavadocMojo.java:5051)
    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeReport (AbstractJavadocMojo.java:2022)
    at org.apache.maven.plugins.javadoc.TestJavadocReport.executeReport (TestJavadocReport.java:153)
    at org.apache.maven.plugins.javadoc.JavadocReport.generate (JavadocReport.java:136)
    at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument (ReportDocumentRenderer.java:226)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render (DefaultSiteRenderer.java:348)
    at org.apache.maven.plugins.site.render.SiteMojo.renderLocale (SiteMojo.java:194)
    at org.apache.maven.plugins.site.render.SiteMojo.execute (SiteMojo.java:143)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] Generating "Source Xref" report   --- maven-jxr-plugin:3.3.0:jxr
[INFO] Generating "Test Source Xref" report --- maven-jxr-plugin:3.3.0:test-jxr
[INFO] Generating "JDepend" report       --- jdepend-maven-plugin:2.0:generate-no-fork

Unknown constant: 18

Unknown constant: 19
[INFO] Generating "dependency-check" report --- dependency-check-maven:7.3.0:check
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (23 ms)
[INFO]

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user�s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.


   About ODC: https://jeremylong.github.io/DependencyCheck/general/internals.html
   False Positives: https://jeremylong.github.io/DependencyCheck/general/suppression.html

? Sponsor: https://github.com/sponsors/jeremylong


[INFO] Analysis Started
[INFO] Finished Archive Analyzer (0 seconds)
[INFO] Finished File Name Analyzer (0 seconds)
[INFO] Finished Jar Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (3 seconds)
[INFO] Finished CPE Analyzer (3 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Finished Unused Suppression Rule Analyzer (0 seconds)
[INFO] Analysis Complete (4 seconds)
[INFO] Writing report to: D:\Entwicklung\Projekte\TemplateEngine\target\site\dependency-check-report.html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:56 min
[INFO] Finished at: 2023-02-14T22:56:15+01:00
[INFO] ------------------------------------------------------------------------
```
