### ISSUE TITLE
[MJAVADOC-584] excludePackageNames is not working as documented anymore

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#880]
**[Thomas Mortagne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tmortagne)** opened **[MJAVADOC-584](https://issues.apache.org/jira/browse/MJAVADOC-584?redirect=false)** and commented

We have the following configuration at XWiki: https://github.com/xwiki/xwiki-commons/blob/xwiki-commons-11.1/pom.xml#L1946. We don't want to produce javadoc for internal packages. This is very similar to the example given on https://maven.apache.org/plugins/maven-javadoc-plugin/examples/exclude-package-names.html.

When I upgrade to 3.1.0 the exclude is not taken into account anymore (I get error related to classes located in internal packages). For example:

```
/home/hudsonagent/jenkins_root/workspace/XWiki_xwiki-commons_master/xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/src/main/java/org/xwiki/extension/version/internal/DefaultVersionConstraint.java:49: error: reference not found

 * @see org.sonatype.aether.util.version.GenericVersionConstraint
```

I noticed MJAVADOC-548 but since the documentation did not changed I assumed my use case was still OK.

---

**Affects:** 3.1.0

**Issue Links:**
- [MJAVADOC-605](https://issues.apache.org/jira/browse/MJAVADOC-605) Exclude packages does not work as described in documentation
 (_**"is duplicated by"**_)
- [MJAVADOC-548](https://issues.apache.org/jira/browse/MJAVADOC-548) Directoryname mixed up with excludePackageNames
 (_**"is caused by"**_)

3 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

The documentation of the parameter was updates (see https://github.com/apache/maven-javadoc-plugin/commit/936cf7d5c91f5f3fa0fc54c1326601432374b112 ) but the example-pages were missed.
In your case your package ends with `internal`, so it doesn't match `\*.internal.\*` anymore because there's no subpackages. A dot is now always a package-separator (which kept the regular expression clean).
A PR to update the documentation is appreciated.

**Comment by jira-importer** [comment]
**[Thomas Mortagne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tmortagne)** commented

> In your case your package ends with internal, so it doesn't match `\*.internal.*` anymore

OK thanks for the hint, I did not noticed it was only for final internal packages.

**Comment by jira-importer** [comment]
**[Thomas Mortagne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tmortagne)** commented

>     a wildcard at the beginning should match 1 or more folders
>     any other wildcard must match exactly one folder

Does it means it not possible anymore to match any number of subpackages ? Like excluding everything under `com.mycompany.myapp.package3` in the example.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

One of both methods in https://github.com/apache/maven-javadoc-plugin/blob/master/src/main/java/org/apache/maven/plugins/javadoc/JavadocUtil.java#L334-L436 is responsible. The seconds contains a comment about the changed behavior.
What I hoped to make clear is that the value of excludePackage is **not** a regular expression, it is closer to an Ant-pattern. The dots (both old and new) are package separators, but it was optional in the old pattern. the value between the dots matches exactly with a folder name.
It looks like there are only integration tests, but this deserves a unittests too. I don't mind adjusting the evaluation, as long as it makes sense and that you can control exclusion of any package.

**Comment by jira-importer** [comment]
**[Thomas Mortagne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tmortagne)** commented

> I don't mind adjusting the evaluation, as long as it makes sense and that you can control exclusion of any package.

I'm fine changing my configuration, I just want to make sure what I think is a very common use case is still taken into account: exclude everything which is part of a package containing an "internal" element in the path.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Having a closer look at the example page, trying to understand the idea behind the exclude expressions:"
* com.mycompany.myapp.package1.\* means exclude every subpackage of `com.mycompany.myapp.package1`, but this package itself is included.
* com.mycompany.myapp.package2 means exclude every package starting with `com.mycompany.myapp.package2`
* \*.util.\* means exclude any package that contains `util`

Do you see the difference between the meaning of an expression ending with `.\*`  depending if it starts with `\*.`? IMHO this is inconsistent. One thing that came up: is `\*.util` allowed and what does it mean? It should have a different meaning compared to `\*.util.\*`, right?

**Comment by jira-importer** [comment]
**[Thomas Mortagne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tmortagne)** commented

I'm not sure we understand each other here. I'm not discussing what is the best syntax, my only concern is finding how I can get my exclude working after upgrading to 3.1.0.

One thing which is written in the current documentation ("any other wildcard must match exactly one folder") seems to suggest that there is no way to exclude something located in all sub folders of a package "internal". Is that true ? Is the document wrong/misleading ?

> One thing that came up: is *.util allowed and what does it mean? It should have a different meaning compared to **.util.**, right?

Sure but again what may concern is how many sub packages does the expression "**.util.**" includes ? The documentation suggest only one.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

> ... how many sub packages does the expression "**.util.**" includes ? The documentation suggest only one.

Did you try it? Looking at the expressions (at first not the documentation) what would make sense?

I'm challenging you a bit here, my experience is that people are bad readers and only "recognize" expressions. Once we agree we can adjust documentation and/or expression resolution.

**Comment by jira-importer** [comment]
**[Thomas Mortagne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tmortagne)** commented

> Did you try it?

Just did and it seems the behaviour contradict the documentation I pasted (it's matching **at least** 1 folder and not **exactly** 1 folder).

> Looking at the expressions (at first not the documentation) what would make sense?

That it match any number of folders but since that's my need and it always worked like this I might be biased :)

**Comment by jira-importer** [comment]
**[Nikolas Falco](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nfalco79)** commented

I got the same issue. We had define as exclded package .internal and now does not work anymore. Changing to .internal* does not matches sub packages as I expected and **.internal.** does not match the internal root package.

Seems now I have to use twice matching patterns **.internal,**.internal.*

It's not immediate and boring also because peoples usually wants exclude a packages with all relative sub packages package. Now they are forced to define rules twice.

**Comment by jira-importer** [comment]
**[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod)** commented

Same here. With 2.10.4 the following is working just fine:

```xml
<excludePackageNames>
    foo.bar.internal
</excludePackageNames>
```

which excludes
`foo.bar.internal.Foo.java`
as well as
`foo.bar.internal.baz.Foo.java`
and
`foo.bar.internal.baz.bing.Foo.java`.

Now with 3.1.0 I have to configure:

```xml
<excludePackageNames>
    foo.bar.internal:
    foo.bar.internal.*
</excludePackageNames>
```

Pretty annoying, given the 14 packages (= now 28 lines) that need to be excluded in my current project.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

The change was about consistency and having full control over all the packages to exclude. If the "everything below package X" is good enough, I don't mind changing that behavior if that helps the community, it simply implies inconsistency of the pattern and not every package structure can be excluded anymore.
